version: '3.8'

services:

  ### 👉 Docker Registry
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - msa-net

  ### 👉 Registry Web UI (📌 pagination 문제 해결됨)
  registry-ui:
    image: joxit/docker-registry-ui:1.5-static
    container_name: registry-ui
    ports:
      - "5001:80"
    environment:
      - REGISTRY_TITLE=Local Docker Registry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    networks:
      - msa-net

  discovery-server:
    build: ./discovery-server
    ports:
      - "9010:9010"
    networks:
      - msa-net

  gateway-service:
    build: ./gateway-service
    ports:
      - "9020:9020"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:9010/eureka
    networks:
      - msa-net

  user-service:
    build: ./user-service
    ports:
      - "9030:9030"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:9010/eureka
    networks:
      - msa-net

  board-service:
    build: ./board-service
    ports:
      - "9040:9040"
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:9010/eureka
    networks:
      - msa-net

networks:
  msa-net:

volumes:
  registry-data: