version: '3'

services:
  registry:
    image: registry:2
    container_name: local-registry
    ports:
      - "5000:5000"
    networks:
      - registry-net

  registry-ui:
    image: requarks/docker-registry-ui
    container_name: registry-ui
    ports:
      - "5001:80"
    environment:
      - REGISTRY_TITLE=Local Docker Registry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    networks:
      - registry-net

networks:
  registry-net: