server:
  port: 9020

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:9010/eureka}