server:
  port: 9010

spring:
  application:
    name: discovery-server

eureka:
  environment: ParkJongkwon

  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

