version: "3"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "28080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: